### ISSUE TITLE
Похоже лишние поля username и password

### ISSUE THREAD

**Issue by TopHlop** [TopHlop/Movie_DB#8]
Похоже лишние поля username и password

_Originally posted by @avegrv in https://github.com/TopHlop/Movie_DB/pull/1#discussion_r514376940_

**Comment by TopHlop** [comment]
Там получается, что при первом запросе request_token они не нужны, поэтому их сохраняю в поля для передачи во второй запрос.

**Comment by avegrv** [comment]
Да, просто можно объеденить в одну Rx цепочку
